#!/usr/bin/env bash
URL=$1
if [[ "$URL" != http://* &&  "$URL" != https://* ]]
then
    URL="http://"$URL
fi
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/slug.sh
SLUG=`slug "$URL"`
mkdir -p /tmp/$SLUG
cd /tmp/$SLUG

for s in 360 760 1260
do
    echo -n $URL" "
    $DIR/getImageDimensions.js $URL $s | 
        awk '{system("'$DIR'/getResizeBenefits.sh \""$1"\" "$2" "$3" "'$s'" "'$s')}' | 
        tee /tmp/$SLUG/results_$s.txt  |
        awk '{optimize_sum += $3;resize_sum+=$5}END{print "Viewport: "'$s',optimize_sum, resize_sum}'
done
